apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-agent
                  key: api-key
            - name: DD_ENV
              value: my-container-test
            - name: DD_LOGS_DIRECT_SUBMISSION_INTEGRATIONS
              value: Serilog
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED
              value: "true"
          image: jenksgibbons/dotnet6serilog:1
          name: web
          ports:
            - containerPort: 80
      restartPolicy: Always
